# .github/workflows/scraper.yml
name: Run Web Scraper

on:
  workflow_dispatch:        # <- required for the green "Run workflow" button
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests beautifulsoup4; fi
      - name: Run scraper
        run: python main.py
